Initial importing vector drawable support
romannurik/AndroidIconAnimator pull request #82
Opened 2016-12-16 00:30 UTC by alexjlockwood

2016-12-22 14:16 UTC, romannurik requested changes

2016-12-22 14:16 UTC, romannurik commented on app/scripts/xmlloader.js
> +export const XmlLoader = {
should this be renamed to something more specific like `VectorDrawableXmlLoader`?

2016-12-22 14:16 UTC, romannurik commented on app/scripts/xmlloader.js
> +          .map(child => nodeToLayerData_(child))
general formatting rule: continuation lines indent 4 spaces instead of 2

2016-12-26 16:24 UTC, alexjlockwood commented on app/scripts/xmlloader.js
> +export const XmlLoader = {
Done.

2016-12-26 16:24 UTC, alexjlockwood commented on app/scripts/xmlloader.js
> +          .map(child => nodeToLayerData_(child))
Done.

2016-12-31 12:12 UTC, merged